backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/backend/**'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/frontend/**'

extension:
  - changed-files:
      - any-glob-to-any-file:
          - 'extensions/**'

release:
  - head-branch: ['^release', 'release']
