version: '3'

services: 
  db:
    image: mongo:4.0.28-xenial
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fluid
      MONGO_INITDB_ROOT_PASSWORD: fluid
      MONGO_INITDB_DATABASE: fluid

  app:
    image: fluid
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports: 
      - 8083:3000
    depends_on: 
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -S -o /dev/null http://localhost:3000/api/health || exit 1"]
      timeout: 20s
      retries: 50
    env_file: ./.env.production.local
