name: Deploy Backend

on:
  workflow_call:
    inputs:
      target:
        description: 'Target to deploy'
        required: true
        default: 'Cloud Run'
        type: string
      version:
        description: 'Package version'
        required: true
        default: ''
        type: string
      package:
        description: 'Package artifact name'
        required: false
        default: 'backend-build'
        type: string
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to deploy'
        required: true
        default: 'Cloud Run'
        type: choice
        options:
          - Cloud Run
          - Compute Engine
      version:
        description: 'Package version'
        required: true
        default: ''
        type: string
      package:
        description: 'Package artifact name'
        required: false
        default: 'backend-build'
        type: string
      run_id:
        description: 'Run ID'
        required: false
        type: string

jobs:
  deploy_to_cloud_run:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.target == 'Cloud Run' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_CLOUD_RUN_DEPLOY_SERVICE_ACCOUNT }}'

      - name: Deploy to Cloud Run
        run: gcloud run deploy fluid-backend --image=us-west1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/fluid/fluid-backend:${{ inputs.version }} --platform=managed --region=us-west1 --allow-unauthenticated --quiet

  deploy_to_compute_engine:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.target == 'Compute Engine' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.package }}
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.DOWNLOAD_ARTIFACTS_PAT }}

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_COMPUTE_ENGINE_DEPLOY_SERVICE_ACCOUNT }}'

      - name: Deploy to Compute Engine
        run: |
          gcloud compute scp backend-build.tar.gz fluid-backend:~/ --tunnel-through-iap
